aemsites/world-bank

blocks/cards/cards.js, blocks/fragment/fragment.js, scripts/aem.js, scripts/editor-support-rte.js, scripts/editor-support.js, scripts/scripts.js, scripts/sidekick.js, tools/sidekick/config.json
Test URLs:
- After: https://<branch>--world-bank--aemsites.hlx.live/
=> convert to xwalk

scripts/dom-helpers.js
No impact JS helper file.
Test URLs:
- After: https://dom-helpers--world-bank--aemsites.hlx.live/
=> add dom-helpers

fstab.yaml
Pointed author to p136806-e1403562.
Test URLs:
- After: https://fstab-update--world-bank--aemsites.hlx.live/
=> Update mount point to DEV instance

styles/styles.css
Fix #18 
JIRA: WRLDBAEMS-71
Test URLs:
- After: https://71-base-styles-v2--world-bank--aemsites.hlx.live/
=> base styles - added colors and spacing

paths.json
Test URLs:
- After: https://base-paths--world-bank--aemsites.hlx.live/
=> adding paths to support multi-languages, jsons

paths.json
Test URLs:
- After: https://base-paths--world-bank--aemsites.hlx.live/
=> adding paths to support navigation json

paths.json
Test URLs:
- After: https://base-paths--world-bank--aemsites.hlx.live/
=> Base paths

.eslintrc.js, component-definition.json, component-filters.json, component-models.json
Fix #[WRLDBAEMS-44](https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-44)
Test URLs:
- After: https://banner-cards--world-bank--aemsites.hlx.live/
=> Banner cards

.eslintrc.js, component-definition.json, component-filters.json, component-models.json
Test URLs:
- After: https://explore-cards--world-bank--aemsites.hlx.live/
=> explore cards block

component-models.json
Fix https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-86
Test URLs:
- After: https://featured-card--world-bank--aemsites.hlx.live/
=> feature cards authoring

component-models.json
Test URLs:
- After: https://explore-cards--world-bank--aemsites.hlx.live/
=> added description filed

component-models.json, styles/styles.css
Test URLs:
- After: https://base-styles--world-bank--aemsites.hlx.live/
=> Base styles

component-definition.json, component-filters.json, component-models.json
Fix #21 
Test URLs:
- After: https://79-data-cards-authoring--world-bank--aemsites.hlx.live/
=> [48] - authoring changes for data-cards

.eslintrc.js, component-models.json
Test URLs:
- After: https://section-swoosh--world-bank--aemsites.hlx.live/
=> Section swoosh

blocks/columns/columns.css
Fix #WRLDBAEMS-86
Test URLs:
- After: https://features-card-bugfix--world-bank--aemsites.hlx.live/en/drafts/thomas/feature-cards
=> Feature-card - bugfix where images in desktop change size on resize

component-models.json
Fix https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-45
Test URLs:
- After: https://button-variations--world-bank--aemsites.hlx.live/
=> Button authoring

blocks/curated-cards/curated-cards.js, component-definition.json, component-models.json
Test URLs:
- After: https://banner-cards--world-bank--aemsites.hlx.live/
=> fixed authoring issue

component-models.json
Reverts aemsites/world-bank#51
Test URLs:
Before: https://main--world-bank--aemsites.hlx.live/
After: https://revert-51-button-variations--world-bank--aemsites.hlx.live/
=> Revert "Button authoring"

component-models.json
Test URLs:
- After: https://page-data--world-bank--aemsites.hlx.live/
=> Adding page metadata in content model

component-models.json, scripts/delayed.js, styles/styles.css
Fix #WRLDBAEMS-113
Test URLs:
- Before: https://main--world-bank--aemsites.hlx.live/en/drafts/mohit/test
- After: https://page-data--world-bank--aemsites.hlx.live/en/drafts/mohit/test
=> Adding page swoosh

component-models.json
Fix https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-59
Test URLs:
- After: https://explore-cards-dialog--world-bank--aemsites.hlx.live/
=> updated dialog

styles/styles.css
Fix #https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-45
Test URLs:
- After: https://buttons--world-bank--aemsites.hlx.live/en/drafts/thomas/buttons
=> Button styles

component-models.json, styles/styles.css
Fix #https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-71
Test URLs:
- After: https://spacing--world-bank--aemsites.hlx.live/
=> base style updates - spacing (M, T & D)

styles/styles.css
Test URLs:
- After: https://fix-spacing-vars--world-bank--aemsites.hlx.live/
=> Added missing variables

.eslintrc.js, component-definition.json, component-filters.json, component-models.json
Fix[ #<gh-issue-id>](https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-106)
Test URLs:
- Before: https://main--world-bank--aemsites.hlx.live/en/drafts/skumawat/mini-cards
- After: https://mini-cards--world-bank--aemsites.hlx.live/en/drafts/skumawat/mini-cards
-
=> authoring changes for mini cards

scripts/delayed.js, styles/styles.css
Test URLs:
- Before: https://main--world-bank--aemsites.hlx.live/en/drafts/mohit/sections
- After: https://page-data--world-bank--aemsites.hlx.live/en/drafts/mohit/sections
=> Adding support of 2nd swoosh on body

blocks/columns/columns.css, blocks/curated-cards/curated-cards.css, blocks/data-cards/data-cards.css, blocks/explore-cards/explore-cards.css, blocks/header/header.css, component-models.json, styles/styles.css
Test URLs:
- After: https://base-style-updates--world-bank--aemsites.hlx.live/
=> Base style updates for fonts and typography

blocks/footer/footer.css, styles/styles.css
Test URLs:
- After: https://link-dark--world-bank--aemsites.hlx.live/
=> Update links for dark theme and update existing to reflect new changes

styles/styles.css
Test URLs:
- After: https://size-updates--world-bank--aemsites.hlx.live/
=> Update missing sizes

blocks/header/header.css, styles/styles.css
Test URLs:
- After: https://nav-menu-font-size-fix--world-bank--aemsites.hlx.live/
=> Nav menu font size fix

.eslintrc.js, blocks/curated-cards/curated-cards.js, blocks/mini-cards/mini-cards.css, blocks/mini-cards/mini-cards.js, component-definition.json, component-models.json
Fix [#<gh-issue-id>](https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-106)
Test URLs:
- Before: https://main--world-bank--aemsites.hlx.live/en/drafts/skumawat/mini-cards
- After: https://mini-cards--world-bank--aemsites.hlx.live/en/drafts/skumawat/mini-cards
- with Heading and Template 
-Desktop
-Tab
-Mobile
=> Mini cards

component-definition.json, component-filters.json, component-models.json
Fix #21 
Test URLs:
- After: https://48-data-card-development--world-bank--aemsites.hlx.live/
=> dialog and template for data cards

blocks/curated-cards/curated-cards.css, blocks/curated-cards/curated-cards.js
Fix #[WRLDBAEMS-131](https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-131)
[WRLDBAEMS-135](https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-135)
[WRLDBAEMS-136](https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-136)
Test URLs:
- After: https://cc-issues--world-bank--aemsites.hlx.live/
=> CSS changes for Curated cards to remove nesting

blocks/curated-cards/curated-cards.js, component-models.json
Fix # WRLDBAEMS-136 
Test URLs:
- After: https://cc-issues--world-bank--aemsites.hlx.live/
=> fixed issues for Curated cards

paths.json
Test URLs:
- After: https://page-data--world-bank--aemsites.hlx.live/
=> adding trending data json entry

blocks/curated-cards/curated-cards.js, paths.json
Fix [RLDBAEMS-38](https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-38)
Test URLs:
- After: https://trending-data--world-bank--aemsites.hlx.live/
=> Trending data

blocks/header/header.js
Test URLs:
- After: https://36-global-header-UI--world-bank--aemsites.hlx.live
=> search container bug

blocks/teaser/teaser.js, component-definition.json, component-models.json
Note- Publish seems to be stripping external URLs out of the block for some reason. I hardcoded WB's sample video as a default to overcome this temporarily on publish but we will want to revisit. @thomsebastin 
Fix #47 https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-47
Test URLs:
- After: https://bugfix-teaser--world-bank--aemsites.hlx.live/en/drafts/michael/teaser
Author URL: https://author-p136806-e1403562.adobeaemcloud.com/content/world-bank/global/en/drafts/michael/teaser.html?ref=bugfix-teaser
=> Bugfix- teaser

blocks/header/header.css
Test URLs:
- After: https://trending-data-bug-header--world-bank--aemsites.hlx.live/en/drafts/thomas/buttons
=> Revert trending data changes causing nav to break

blocks/tabs/tabs.css, component-definition.json, component-filters.json, component-models.json
Fix #WRLDBAEMS-77
Test URLs:
- After: https://tabs--world-bank--aemsites.hlx.live/
=> authoring changes for tabs block

component-filters.json
Fix #WRLDBAEMS-77
Test URLs:
- After: https://tabs--world-bank--aemsites.hlx.live/
=> updated model defination

blocks/header/header.css, blocks/header/header.js
Test URLs:
- After: https://header-bugs--world-bank--aemsites.hlx.live/
=> nav not showing in mobile

blocks/header/header.css
Fix #https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-166
https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-167
https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-168
Test URLs:
- After: https://nav-menu-bug-fixes--world-bank--aemsites.hlx.live/
=> Nav menu bug fixes

component-definition.json, component-models.json
Fix #77
Test URLs:
- Before: https://main--world-bank--aemsites.hlx.live/en/drafts/skumawat/tabs
- After: https://tabs--world-bank--aemsites.hlx.live/en/drafts/skumawat/tabs
=> update frgment path to string

blocks/header/header.css, blocks/header/header.js, package-lock.json, package.json
Test URLs:
- After: https://nav-bug-fix--world-bank--aemsites.hlx.live/
=> Nav bug fix

styles/styles.css
Test URLs:
- After: https://global-updates--world-bank--aemsites.hlx.live/
=> adding global line height and update to colors

component-definition.json, component-filters.json, component-models.json
Test URLs:
- Before: https://83-our-priority--world-bank--aemsites.hlx.live/
- After: https://<branch>--world-bank--aemsites.hlx.live/
=> 83 our priority

blocks/columns/columns.css, scripts/delayed.js, styles/lazy-styles.css, styles/styles.css
Test URLs:
- After: https://page-data--world-bank--aemsites.hlx.live/
=> Performance - moved swoosh in lazy.css

component-definition.json, component-filters.json, component-models.json
Fix #77
Test URLs:
- Before: https://main--world-bank--aemsites.hlx.live/en/drafts/skumawat/tabs
- After: https://tabs--world-bank--aemsites.hlx.live/en/drafts/skumawat/tabs
=> authoring for leadership list

blocks/data-cards/data-cards.css
Test URLs:
- After: https://sticky-on-scroll--world-bank--aemsites.hlx.live/
=> Sticky on scroll - data for development

.eslintrc.js, component-definition.json, component-filters.json, component-models.json
Test URLs:
- After: https://96-biodetail--world-bank--aemsites.hlx.live/en/drafts/naina/bio-detail?ref=96-biodetail
=> 96 biodetail (added component definition)

blocks/header/header.js, scripts/delayed.js, styles/lazy-styles.css
Fix #https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-208
Test URLs:
- After: https://cookie-bug208-fix--world-bank--aemsites.hlx.page/
It's reproducible in browser emulator, Samsung galaxy S8+
=> Updated lazy-styles.css to fix WRLDBAEMS-208 bug

blocks/columns/columns.css, styles/styles.css
Test URLs:
- After: https://feature-card-bugfix--world-bank--aemsites.hlx.live/en/drafts/thomas/feature-cards
=> Feature cards bugfix

component-definition.json, component-filters.json, component-models.json
Test URLs:
- After: https://wrldbaems-87-config--world-bank--aemsites.hlx.live/
=> WRLDBAEMS-87-config: Carousel

blocks/cards/cards.css, component-definition.json, component-models.json
Test URLs:
- After: https://wrldbaems-75-leadership-bug-fix--world-bank--aemsites.hlx.page/en/drafts/pritam/leadership
=> Wrldbaems 75 leadership bug fix

blocks/curated-cards/curated-cards.css
Fix #WRLDBAEMS-186
Test URLs:
- After: https://cards-issues--world-bank--aemsites.hlx.live/
=> updated CSS for issues

component-models.json
Fix # Fix to have alt text for Image Block. It was not showing alt text wherever, Image block has been used
Test URLs:
- After: https://wrldbaems-86-bug-fixes--world-bank--aemsites.hlx.page/en/drafts/pritam/feature-cards
=> Wrldbaems 86 bug fixes

blocks/tabs/tabs.js, component-definition.json, component-models.json
Test URLs:
- Before: https://main--world-bank--aemsites.hlx.live/en/drafts/skumawat/tabs
- After: https://tabs-issues--world-bank--aemsites.hlx.live/
=> changes for tabs issues

blocks/header/header.css, blocks/header/header.js, blocks/header/navigation.js
Test URLs:
- After: https://header-issue-fix--world-bank--aemsites.hlx.live/
=> Header issue fix

blocks/priority-list/priority-list.css
Test URLs:
- After: https://priority-list-issue--world-bank--aemsites.hlx.live/en/drafts/padmashree/our-priorities-cards
=> [fix] priority-list UAT issue

blocks/priority-list/priority-list.css
Test URLs:
- After: https://priority-list-issue--world-bank--aemsites.hlx.live/en/drafts/padmashree/our-priorities-cards
=> Priority list issue

helix-query.yaml
Test URLs:
- After: https://WRLDBAEMS-226-query-index-1--world-bank--aemsites.hlx.live/
=> exclude drafts and nav and footer

blocks/data-cards/data-cards.css
Test URLs:
- Before: https://main--world-bank--aemsites.hlx.live
- After: https://dynamic-cards-css-link--world-bank--aemsites.hlx.live
=> css issue in link

blocks/cards/cards.css
Fix # [WRLDBAEMS-76](https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-76)
Test URLs:
- Before: [https://main--world-bank--aemsites.hlx.live/en/drafts/akash/senior-leadership](https://main--world-bank--aemsites.hlx.live/en/drafts/akash/senior-leadership)
- After: [https://wrldbaems-76-senior-leadership--world-bank--aemsites.hlx.live/en/drafts/akash/senior-leadership](https://wrldbaems-76-senior-leadership--world-bank--aemsites.hlx.live/en/drafts/akash/senior-leadership)
=> WRLDBAEMS-76 senior leadership card css changes

blocks/priority-list/priority-list.css
Test URLs:
- After: https://list-issue--world-bank--aemsites.hlx.page/
=> [fix] last-image-hidden

component-models.json, paths.json, styles/styles.css
Fix #WRLDBAEMS-97
Test URLs:
- After: https://tabs-issues--world-bank--aemsites.hlx.live/
=> Authoring changes for tab for apis

blocks/footer/footer.css
Fix [WRLDAEMS-144](https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-144)
Test URLs:
- After: https://wrldbarms-144--world-bank--aemsites.hlx.live/
=> WRLDAEMS-144

.eslintrc.js, component-models.json
Test URLs:
- After: https://section-fix--world-bank--aemsites.hlx.live/
=> Section to support bg image

blocks/cards/cards.css
Fix #https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-241
Test URLs:
- Before: https://main--world-bank--aemsites.hlx.live/en/drafts/qa/story-75
- After: https://wrldbaems-241-bug-fix--world-bank--aemsites.hlx.page/en/drafts/qa/story-75
=> Wrldbaems 241 bug fix

blocks/data-cards/data-cards.css, scripts/scripts.js, scripts/utils.js, styles/styles.css
Test URLs:
- Before: https://main--world-bank--aemsites.hlx.live/en/drafts/mohit/test-page
- After: https://section-fix--world-bank--aemsites.hlx.live/en/drafts/mohit/test-page
=> Supporting bg images for Sections

scripts/slider.js, styles/slider.css
Fix [WRLDBAEMS-275](https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-275)
Test URLs:
- After: [https://wrldbaems-275--world-bank--aemsites.hlx.live/](https://wrldbaems-275--world-bank--aemsites.hlx.live/)
=> WRLDBAEMS-274: Carousel Feedback

blocks/heading/heading.css, styles/styles.css
Test URLs:
- After: https://headingfixes--world-bank--aemsites.hlx.live/en/drafts/arjun/headingblock
=> heading block fixes

component-models.json
Fix #https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-279
Test URLs:
- After: https://mini-card-variation--world-bank--aemsites.hlx.live/
=> Image list variation

blocks/columns/columns.css
Reverts aemsites/world-bank#237
Test URLs:
- Before: https://columns-bug-fix--world-bank--aemsites.hlx.live/
- After: https://revert-237-columns-bug-fix--world-bank--aemsites.hlx.live/
=> Revert "Fix font-sizes, line-heights and spacing issues for columns block"

blocks/signup/signup.css
Test URLs:
- After: https://variables-email-signup--world-bank--aemsites.hlx.live/
=> Signup block to use wb variables

blocks/columns/columns.css, component-models.json
Fix #246
Test URLs:
- Before: https://main--world-bank--aemsites.hlx.live/en/who-we-are
- After: https://Heading-with-description-variation--world-bank--aemsites.hlx.live/en/who-we-are
Here added new variation for columns block called Heading with description.
=> Add new Variation for columns block called Heading with Description

blocks/research-publications-cards/research-publications-cards.css
Test URLs:
- After: https://res-pub-variables--world-bank--aemsites.hlx.live/
=> research and publications variable updates

blocks/measuring-impact-cards/measuring-impact-cards.css
Test URLs:
- After: https://variables-measuring-impact--world-bank--aemsites.hlx.live/en/drafts/pritam/who-we-are
=> Update measuring our impact with new variables

styles/slider.css
Fix [WRLDBAEMS-275](https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-275)
Test URLs:
- After: [https://wrldbaems-275-feedback--world-bank--aemsites.hlx.live/](https://wrldbaems-275-feedback--world-bank--aemsites.hlx.live)
=> WRLDBAEMS-275: Feedback

blocks/mini-cards/mini-cards.css
Test URLs:
- After: https://variables-mini-cards--world-bank--aemsites.hlx.live/
=> Mini cards to use variables

blocks/explore-cards/explore-cards.css
Test URLs:
- After: https://variables-explore-cards--world-bank--aemsites.hlx.live/
=> Explore cards variables integration

blocks/tabs/tabs.js
Fix #WRLDBAEMS-287
Test URLs:
- Before: https://main--world-bank--aemsites.hlx.live/en/leadership
- After: https://tabs-bugs--world-bank--aemsites.hlx.live/en/leadership
=> bug fix for manual tab

blocks/curated-cards/curated-cards.js, blocks/mini-cards/mini-cards.js, blocks/signup/signup.js, blocks/teaser/teaser.js
Test URLs:
- After: https://code-cleanup--world-bank--aemsites.hlx.live/
=> fixed performance issue with homepage

blocks/footer/footer.css
Test URLs:
- After: https://var-footer--world-bank--aemsites.hlx.live/
=> Footer to use variables from WB

blocks/data-cards/data-cards.css
Test URLs:
- After: https://var-data-cards--world-bank--aemsites.hlx.live/
=> Variable updates for data cards block

blocks/data-cards/data-cards.css
Fix #264
Test URLs:
- After: https://news-cards-variation-spacing-fixes--world-bank--aemsites.hlx.live/
=> Spacing fix

blocks/priority-list/priority-list.css
Test URLs:
- After: https://var-priority-list--world-bank--aemsites.hlx.live/en/who-we-are
=> Updated priority list block to use variables

blocks/organizational-cards/organizational-cards.js, blocks/priority-list/priority-list.js
Test URLs:
- Before: https://main--world-bank--aemsites.hlx.live/en/who-we-are
- After: https://code-cleanup--world-bank--aemsites.hlx.live/en/who-we-are
=> fixed accessibility issues

blocks/cards/cards.css
Test URLs:
- After: https://cards-variables-changes--world-bank--aemsites.hlx.page/en/leadership
=> Updated Cards.css to use variables defined in Styles.css

blocks/carousel/carousel.css, styles/slider.css
Test URLs:
- After: https://var-carousel--world-bank--aemsites.hlx.live/en/who-we-are
=> Carousel updates

styles/styles.css
Test URLs:
- After: https://var-global-update--world-bank--aemsites.hlx.live/
=> Changes to mobile typography values

blocks/cards/cards.css
Fix #NO-JIRA
Test URLs:
- Before: [https://main--world-bank--aemsites.hlx.live/en/leadership](https://main--world-bank--aemsites.hlx.live/en/leadership)
- After: [https://wrldbaems-senior-leadership--world-bank--aemsites.hlx.live/en/leadership](https://wrldbaems-senior-leadership--world-bank--aemsites.hlx.live/en/leadership)
=> replaced h4 styles with h3

blocks/block-quote/block-quote.css
Test URLs:
- Before: https://main--world-bank--aemsites.hlx.live/en/leadership/bio-detail
- After: https://block-quote-var--world-bank--aemsites.hlx.page/en/leadership/bio-detail
=> Updated block-quote.css to use base styles varibales

blocks/tabs/tabs.css, styles/styles.css
Test URLs:
- After: https://variables-tabs--world-bank--aemsites.hlx.live/en/leadership
=> Updates tabs block to use variables

blocks/curated-cards/curated-cards.css
Test URLs:
- After: https://var-curated-cards--world-bank--aemsites.hlx.live/
=> Var curated cards

blocks/priority-list/priority-list.js, component-models.json
Test URLs:
- After: https://pl-issues-updated--world-bank--aemsites.hlx.live/
=> Pl issues updated

blocks/bio-detail/bio-detail.css, blocks/columns/columns.css, blocks/research-publications-cards/research-publications-cards.css
Test URLs:
- After: https://home-bugs--world-bank--aemsites.hlx.live
=> Home bugs(new variable for research and publication section)

blocks/breadcrumb/breadcrumb.css
Fix # NO-JIRA
Test URLs:
- Before: https://main--world-bank--aemsites.hlx.live/en/leadership
- After: https://wrldbaems-78-breadcrumb-padding-fix--world-bank--aemsites.hlx.live/en/leadership
=> fixed padding for breadcrumb

blocks/data-cards/data-cards.css
Test URLs:
- After: https://data-cards-n-empowering-people--world-bank--aemsites.hlx.live/
=> left section of data card variations

component-models.json
Fix #https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-296
https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-295
https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-297
Test URLs:
- After: https://blockbugfixes--world-bank--aemsites.hlx.live/
=> Metadata bug fixes

blocks/breadcrumb/breadcrumb.css, blocks/cards/cards.css, blocks/header/header.css, blocks/leaders-list/leaders-list.css, blocks/research-publications-cards/research-publications-cards.css, blocks/tabs/tabs.css
Test URLs:
- After: https://link-variable--world-bank--aemsites.hlx.live/
=> Design feedback on links to use a specific variable

blocks/columns/columns.css, blocks/research-publications-cards/research-publications-cards.css
Test URLs:
- After: https://home-bugs--world-bank--aemsites.hlx.live/
=> some corrections related to font size

.eslintrc.js, blocks/bio-detail/bio-detail.js, blocks/footer/footer.js, component-models.json, scripts/delayed.js, scripts/scripts.js, scripts/utils.js
Test URLs:
- After: https://analytics--world-bank--aemsites.hlx.live/
=> Analytics implementation

blocks/organizational-cards/organizational-cards.css
Fix various visual issues with spacing, button colors.
Fix # https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-266, https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-271
Test URLs:
- Before: https://main--world-bank--aemsites.hlx.live/en/who-we-are
- After: https://bugfixes-5insts--world-bank--aemsites.hlx.live/en/who-we-are
=> Bugfixes - Image with Hover Cards (Five Institutions)

blocks/data-cards/data-cards.css, blocks/header/header.css, blocks/heading/heading.css, blocks/organizational-cards/organizational-cards.css, styles/styles.css
Test URLs:
- After: https://var-updates--world-bank--aemsites.hlx.live/
=> Remove heading variables

styles/styles.css
Test URLs:
- After: https://size-variables--world-bank--aemsites.hlx.live/
=> Remove size variables

blocks/bio-detail/bio-detail.css, blocks/breadcrumb/breadcrumb.css, blocks/header/header.css, blocks/heading/heading.css, blocks/priority-list/priority-list.css, styles/lazy-styles.css, styles/styles.css
Test URLs:
- After: https://body-var-update--world-bank--aemsites.hlx.live/
=> Body variable updates

styles/slider.css
Fix # [WRLDBAEMS-275](https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-275)
Test URLs:
- After: https://WRLDBAEMS-275-qa-changes--world-bank--aemsites.hlx.live/
=> WRLDBAEMS-275: QA Changes

scripts/scripts.js, scripts/utils.js, styles/styles.css
Test URLs:
- After: https://analytics--world-bank--aemsites.hlx.live/
=> Added dir="rtl" on html tag for Arabic language

blocks/bio-detail/bio-detail.css, blocks/columns/columns.css, blocks/header/header.css, styles/styles.css
Test URLs:
- After: https://spacing-vars--world-bank--aemsites.hlx.live/
=> Remove old spacing vars

blocks/bio-detail/bio-detail.css, blocks/breadcrumb/breadcrumb.css, blocks/header/header.css, blocks/heading/heading.css, blocks/live-now/live-now.css, blocks/organizational-cards/organizational-cards.css, styles/lazy-styles.css, styles/styles.css
Test URLs:
- After: https://remove-colors--world-bank--aemsites.hlx.live/
=> Replace primary blues

blocks/signup/signup.js
Test URLs:
- After: https://signupfixes--world-bank--aemsites.hlx.live/
=> Added check for already subscribed 

blocks/footer/footer.js, blocks/header/header.js, paths.json, scripts/scripts.js, scripts/utils.js
Test URLs:
- Before: https://main--world-bank--aemsites.hlx.live/ext/en/who-we-are
- After: https://msm--world-bank--aemsites.hlx.live/ext/en/who-we-are
=> added /ext in url requests

blocks/columns/columns.css, blocks/data-cards/data-cards.css
Test URLs:
- After: https://homepage-rtl--world-bank--aemsites.hlx.live/ext/en/home
=> Homepage rtl

blocks/data-cards/data-cards.css, blocks/priority-list/priority-list.css, styles/styles.css
Test URLs:
- After: https://priority-colors--world-bank--aemsites.aem.live/ext/en/home
=> Updated priority colors

blocks/breadcrumb/breadcrumb.css, blocks/cards/cards.css, blocks/heading/heading.css, blocks/leaders-list/leaders-list.css, blocks/mini-cards/mini-cards.css, blocks/tabs/tabs.css
Fix :
https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-330
https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-344
https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-339
Test URLs:
- After: https://leadshipfixes--world-bank--aemsites.aem.live/ext/en/drafts/arjun/leadership
=> leadership page fixes

blocks/curated-cards/curated-cards.css, blocks/data-cards/data-cards.css, blocks/explore-cards/explore-cards.css, blocks/header/header.css, styles/styles.css
Fix # WRLDBAEMS-308, WRLDBAEMS-315
Test URLs:
- After: https://uatbug-home--world-bank--aemsites.aem.live/ext/en/home
=> Uatbug home

styles/slider.css
Fix [WRLDBAEMS-275](https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-275)
Test URLs:
- After: https://WRLDBAEMS-275-fixes--world-bank--aemsites.aem.live/ext/en/who-we-are
=> WRLDBAEMS-275: Minor fixes

blocks/cards/cards.css, blocks/heading/heading.css, blocks/leaders-list/leaders-list.css, blocks/teaser/teaser.css
Test URLs:
- Before: https://main--world-bank--aemsites.aem.live/ext/ar/leadership
- After: https://leadership-arabic-styles--world-bank--aemsites.aem.live/ext/ar/leadership
=> Leadership arabic styles

blocks/bio-detail/bio-detail.css, blocks/mini-cards/mini-cards.css, blocks/tabs/tabs.css
Test URLs:
- Before: https://main--world-bank--aemsites.aem.live/ext/en/leadership/axel-van-trotsenburg
- After: https://variable-name-change-for-bio-detail-page--world-bank--aemsites.aem.live/ext/en/leadership/axel-van-trotsenburg
=> Variable name changes for bio-detail page

blocks/curated-cards/curated-cards.js, blocks/data-cards/data-cards.js, blocks/mini-cards/mini-cards.js, component-models.json
Test URLs:
- After: - https://alt-to-cards-images--world-bank--aemsites.aem.page/ext/en/home
=> Alt to cards images

.eslintrc.js, blocks/heading/heading.css, component-filters.json, component-models.json
Test URLs:
- After: https://headingenhancement--world-bank--aemsites.aem.live/
=> Heading enhancement

blocks/teaser/teaser.css
Test URLs:
- After: https://video-block-fix--world-bank--aemsites.aem.live/ext/en/home
=> Video block fix

blocks/bio-detail/bio-detail.css, styles/styles.css
Test URLs:
- After: https://biodetail-rtl--world-bank--aemsites.hlx.live/ext/ar/leadership/axel-van-trotsenburg
=> biodetail-rtl

blocks/carousel/carousel.css, styles/slider.css
Fix [WRLDBAEMS-275](https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-275)
Test URLs:
- After: https://WRLDBAEMS-275-minor-fixes--world-bank--aemsites.hlx.live/
=> WRLDBAEMS-275: minor-fixes

blocks/organizational-cards/organizational-cards.css
Test URLs:
- After: https://institutions-animation--world-bank--aemsites.aem.live/ext/en/who-we-are
=> Change animation style for institutional cards

blocks/columns/columns.css, styles/slider.css
Fix #WRLDBAEMS-329
Test URLs:
- Before: https://main--world-bank--aemsites.hlx.live/ext/en/who-we-are
- After: https://sys-var--world-bank--aemsites.hlx.live/ext/en/who-we-are
=> sytle-system changes for column

blocks/data-cards/data-cards.css
Test URLs:
- After: https://data-card-issue--world-bank--aemsites.aem.page/
=> tag color issue fixed

blocks/bio-detail/bio-detail.css
Test URLs:
- After: https://biodetail-bugs--world-bank--aemsites.hlx.live/ext/en/leadership/axel-van-trotsenburg
=> spacing issue

blocks/data-cards/data-cards.css
Fix #350
Test URLs:
- After: https://news-card-bug--world-bank--aemsites.aem.live/ext/en/home
Minor padding changes in news card
=> news card bug

blocks/columns/columns.css, blocks/curated-cards/curated-cards.css, blocks/data-cards/data-cards.css, blocks/explore-cards/explore-cards.css, blocks/measuring-impact-cards/measuring-impact-cards.css, blocks/research-publications-cards/research-publications-cards.css, blocks/signup/signup.css, styles/styles.css
Pending Items
**Explore Cards
Latest From World Bank
Footer** 
Test URLs:
- After: https://homePageDesignVariables--world-bank--aemsites.aem.live/
=> Home page design variables

blocks/columns/columns.css, blocks/data-cards/data-cards.css
Test URLs:
- After: https://Tranforming-kldge-spacing--world-bank--aemsites.hlx.live/
=> Tranforming kldge spacing

component-definition.json, component-filters.json, component-models.json
Test URLs:
- Before: https://main--world-bank--aemsites.hlx.live/ext/en/home
- After: https://refactoring--world-bank--aemsites.hlx.live/ext/en/home
=> Fragment block

blocks/explore-cards/explore-cards.css
Fix https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-156
Test URLs:
- After: https://explorecards--world-bank--aemsites.aem.live/ext/en/drafts/arjun/sample2
=> Explore cards

blocks/data-cards/data-cards.css
Fix #358
Test URLs:
- After: https://data-cards-final-fixes--world-bank--aemsites.hlx.live/
Fixed small spacing issues.
=> Fix some bugs

blocks/data-cards/data-cards.css
Fix #359
Test URLs:
- Before: https://main--world-bank--aemsites.hlx.live/ext/en/home
- After: https://newscard-layout-bug--world-bank--aemsites.hlx.live/ext/en/home
Fixing a few newscard layout bugs
=> newscard layout bug fix

blocks/curated-cards/curated-cards.js, blocks/mini-cards/mini-cards.js
Fix #WRLDBAEMS-341
Test URLs:
- After: https://cc-placeholder--world-bank--aemsites.hlx.live/
=> updated for fetching data from placeholders

blocks/heading/heading.css, scripts/scripts.js, styles/styles.css
Fix #WRLDBAEMS-243
Test URLs:
- Before: https://main--world-bank--aemsites.hlx.live/ext/en/who-we-are
- After: https://heading-update--world-bank--aemsites.hlx.live/ext/en/who-we-are
=> Heading update

blocks/live-now/live-now.css
Fix #WRLDBAEMS-224
Test URLs:
- Before: https://main--world-bank--aemsites.hlx.live/fr/home
- After: https://live-now-fix--world-bank--aemsites.hlx.live/fr/home
=> fix for live-now modal translation

blocks/cards/cards.css
https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-352
Test URLs:
- After: https://leadership-bugfix--world-bank--aemsites.hlx.live/
=> Leadership bugfix - WRLDBAEMS-352

blocks/breadcrumb/breadcrumb.js, scripts/scripts.js
Fix # [WRLDBAEMS-358](https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-358)
Test URLs:
- Before: [https://main--world-bank--aemsites.hlx.live/ext/en/leadership/axel-van-trotsenburg](https://main--world-bank--aemsites.hlx.live/ext/en/leadership/axel-van-trotsenburg)
- After: [https://wrldbaems-358-updated-search-query-path--world-bank--aemsites.hlx.live/ext/en/leadership/axel-van-trotsenburg](https://wrldbaems-358-updated-search-query-path--world-bank--aemsites.hlx.live/ext/en/leadership/axel-van-trotsenburg)
=> updated search query path to support ext in url

blocks/leaders-list/leaders-list.css, blocks/tabs/tabs.css
Fix #WRLDBAEMS-290
Test URLs:
- Before: https://main--world-bank--aemsites.hlx.live/ext/en/leadership
- After: https://tab-ui-fix--world-bank--aemsites.hlx.live/ext/en/leadership
=> updated line height issues

blocks/columns/columns.css, blocks/curated-cards/curated-cards.css, blocks/data-cards/data-cards.css, blocks/header/header.css, blocks/measuring-impact-cards/measuring-impact-cards.css, blocks/organizational-cards/organizational-cards.css, blocks/priority-list/priority-list.css
Test URLs:
- Before: https://main--world-bank--aemsites.hlx.live/ext/en/home
- After: https://refactoring--world-bank--aemsites.hlx.live/ext/en/home
=> fixed hover issues

blocks/breadcrumb/breadcrumb.css, blocks/breadcrumb/breadcrumb.js
Fix # NO-JIRA
Test URLs:
- Before: [https://main--world-bank--aemsites.hlx.live/ext/en/leadership/axel-van-trotsenburg](https://main--world-bank--aemsites.hlx.live/ext/en/leadership/axel-van-trotsenburg)
- After: [https://wrldbaems-breadcrumb-ui-fix--world-bank--aemsites.hlx.live/ext/en/leadership/axel-van-trotsenburg](https://wrldbaems-breadcrumb-ui-fix--world-bank--aemsites.hlx.live/ext/en/leadership/axel-van-trotsenburg)
=> removed max width for breadcrumb title

blocks/leaders-list/leaders-list.css, blocks/tabs/tabs.css, blocks/tabs/tabs.js
Fix #WRLDBAEMS-290
Test URLs:
- Before: https://main--world-bank--aemsites.hlx.live/ext/en/leadership
- After: https://tab-ui-fix--world-bank--aemsites.hlx.live/ext/en/leadership
=> tabs and leader list ui fixes

blocks/tabs/tabs.css, blocks/tabs/tabs.js
Test URLs:
- Before: https://main--world-bank--aemsites.hlx.live/ext/en/leadership
- After: https://tab-acc--world-bank--aemsites.hlx.live/ext/en/leadership
=> accessiblity update for tabs

styles/slider.css
Test URLs:
- After: https://carousel-alignment-issue--world-bank--aemsites.aem.page/ext/en/who-we-are
=> carousel alignment fix

helix-query.yaml, helix-sitemap.yaml
Test URLs:
- After: https://refactoring--world-bank--aemsites.aem.live/ext/en/home
=> Refactoring

component-models.json
Test URLs:
- After: https://priority-list-tagissue--world-bank--aemsites.aem.page/ext/en/who-we-are
=> Updated to fix to Tag issue on priority-list

blocks/cards/cards.css, blocks/tabs/tabs.css, scripts/scripts.js, styles/styles.css
Test URLs:
- After: https://refactoring--world-bank--aemsites.aem.live/ext/en/home
=> fixed hover and accessibility issues

blocks/dynamic-media-asset/dynamic-media-asset.js
Test URLs:
- After: https://dm-asset--world-bank--aemsites.aem.live/
=> Set for main

blocks/tabs/tabs.js
Test URLs:
- After: https://tabs-issue-fix--world-bank--aemsites.aem.live/ext/en/who-we-are/leadership/axel-van-trotsenburg
Issues: it fixed visiblity show more button when there is nor results from api.
=> null check to not show more button

styles/styles.css
Test URLs:
- After: https://tag-colors--world-bank--aemsites.aem.live/ext/en/home
=> Updates to tag colors as per WB

blocks/signup/signup.css
Fix #https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-375
Test URLs:
- After: https://newletterfixes--world-bank--aemsites.aem.live/ext/en/home
=> News letter padding spacing fixes

package-lock.json, package.json
Test URLs:
- After: https://header-ally-issue--world-bank--aemsites.aem.page/ext/en/home
=> reverted package file changes

blocks/signup/signup.css
Test URLs:
- Before: https://main--world-bank--aemsites.aem.live/ext/ar/home
- After: https://ar-newsletter--world-bank--aemsites.aem.live/ext/ar/home
=> Newsletter border radius tweaked

blocks/data-cards/data-cards.css, blocks/signup/signup.css
Test URLs:
- After: https://arabic-bugs--world-bank--aemsites.hlx.live/ext/ar/home
=> changing arrow direction and signup icon

blocks/breadcrumb/breadcrumb.css
Fix # NO-JIRA
Test URLs:
- Before: [https://main--world-bank--aemsites.hlx.live/ext/en/who-we-are/leadership/axel-van-trotsenburg](https://main--world-bank--aemsites.hlx.live/ext/en/who-we-are/leadership/axel-van-trotsenburg)
- After: [https://breadcrumb-padding-change--world-bank--aemsites.aem.live/ext/en/who-we-are/leadership/axel-van-trotsenburg](https://breadcrumb-padding-change--world-bank--aemsites.aem.live/ext/en/who-we-are/leadership/axel-van-trotsenburg)
=> changed padding and line-height as per figma

blocks/priority-list/priority-list.css, blocks/priority-list/priority-list.js, component-models.json
Test URLs:
- After: https://alt-refactor--world-bank--aemsites.aem.live/ext/en/who-we-are
=> Alt refactor

blocks/priority-list/priority-list.css
Test URLs:
- After: https://priority-padding--world-bank--aemsites.aem.live/ext/en/who-we-are
=> priority-padding fixed

blocks/breadcrumb/breadcrumb.css, blocks/cards/cards.css
Test URLs:
- After: https://priority-padding-fixes--world-bank--aemsites.aem.live/ext/en/who-we-are
=> margin padding fixed

blocks/cards/cards.css, blocks/cards/cards.js, blocks/organizational-cards/organizational-cards.js
Test URLs:
- After: https://a11y-issues-v2--world-bank--aemsites.aem.live/ext/en/who-we-are
=> Update button role and remove list item for profile summary

blocks/organizational-cards/organizational-cards.js
Test URLs:
- After: https://organisation-a11y--world-bank--aemsites.aem.live/ext/en/who-we-are
=> Improve tab navigation and readout for "5 institution" cards

blocks/signup/signup.css, blocks/signup/signup.js
Fix # WRLDBAEMS-385 -  Fixed 3 and 4 accessibility issue
Test URLs:
- Before: https://main--world-bank--aemsites.aem.page/ext/en/home
- After: https://fix-accessibility-signup--world-bank--aemsites.aem.page/ext/en/home
=> Fix accessibility signup

blocks/research-publications-cards/research-publications-cards.js
Test URLs:
- After: https://research-a11y--world-bank--aemsites.aem.live/ext/en/home
=> Disable focus on image in research and publications block

blocks/measuring-impact-cards/measuring-impact-cards.css, blocks/tabs/tabs.css
Fix # UAT: space below hover line in Tabs 
Test URLs:
- Before: https://main--world-bank--aemsites.aem.live/ext/en/who-we-are/leadership
- After: https://uat-sourabh--world-bank--aemsites.aem.live/ext/en/who-we-are/leadership
=> uat : tabs hover line space issue

blocks/header/header.js
Test URLs:
- After: https://main-menu-a11y--world-bank--aemsites.aem.live/ext/en/who-we-are/leadership/axel-van-trotsenburg
=> Main menu navigation accessibility issues

blocks/data-cards/data-cards.js, blocks/header/header.css, blocks/header/header.js
Test URLs:
- After: https://rtl-bugs--world-bank--aemsites.hlx.live/ext/ar/home
=> Rtl bugs  (navbar arrows in arabic corrected)

blocks/bio-detail/bio-detail.css
Test URLs:
- After: https://bio-a11y--world-bank--aemsites.aem.live/ext/en/who-we-are/leadership/axel-van-trotsenburg
=> Fix for bio-detail tab ordering in mobile

blocks/curated-cards/curated-cards.js, blocks/dynamic-media-asset/dynamic-media-asset.css, blocks/dynamic-media-asset/dynamic-media-asset.js, component-models.json, scripts/scripts.js
https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-390
Test URLs:
- Before: https://main--world-bank--aemsites.aem.page/ext/en/drafts/qa/feature-card
- After: https://dm-asset-update--world-bank--aemsites.aem.page/ext/en/drafts/qa/feature-card
=> Add DM Asset to Curated Card

blocks/bio-detail/bio-detail.js, blocks/curated-cards/curated-cards.js, blocks/tabs/tabs.js, scripts/utils.js
Test URLs:
- After: https://dm-asset-update--world-bank--aemsites.aem.live/ext/en/home
=> Corrected curated cards to support DM images

blocks/footer/footer.css
Test URLs:
- After: https://footer-hover-style--world-bank--aemsites.aem.live/ext/en/home
=> hover styling on footer

blocks/curated-cards/_curated-cards.json, blocks/curated-cards/curated-cards.js
Test URLs:
- After: https://curated-cards-bugfix--world-bank--aemsites.aem.live/ext/en/home
=> Curated cards additional checks

blocks/curated-cards/_curated-cards.json, blocks/curated-cards/curated-cards.js, component-models.json
Test URLs:
- After: https://read-more-fix--world-bank--aemsites.aem.live/
=> updated curated cards

blocks/block-quote/block-quote.css, blocks/cards/cards.css, blocks/columns/columns.css, blocks/curated-cards/curated-cards.css, blocks/data-cards/data-cards.css, blocks/explore-cards/explore-cards.css, blocks/footer/footer.css, blocks/header/header.css, blocks/heading/heading.css, blocks/leaders-list/leaders-list.css, blocks/live-now/live-now.css, blocks/measuring-impact-cards/measuring-impact-cards.css, blocks/mini-cards/mini-cards.css, blocks/organizational-cards/organizational-cards.css, blocks/priority-list/priority-list.css, blocks/research-publications-cards/research-publications-cards.css, blocks/tabs/tabs.css, styles/slider.css, styles/styles.css
Test URLs:
- Before: https://main--world-bank--aemsites.aem.live/ext/ar/home
- After: https://handoff-bugs--world-bank--aemsites.aem.live/ext/ar/home
=> Change Arabic bold weights to 400

paths.json
Test URLs:
- After: https://tags--world-bank--aemsites.aem.live/ext/en/home
=> adding taxonomy support

blocks/footer/footer.css, blocks/measuring-impact-cards/measuring-impact-cards.css, blocks/mini-cards/mini-cards.css
Test URLs:
- After: https://fix-russian--world-bank--aemsites.aem.page/ext/en/home
=> Fix russian

blocks/curated-cards/curated-cards.js, blocks/data-cards/data-cards.js, blocks/explore-cards/explore-cards.js, blocks/mini-cards/mini-cards.js, paths.json, scripts/utils.js
Test URLs:
- After: https://tags--world-bank--aemsites.aem.live/ext/en/home
=> implemented taxonomy json and updated dependent blocks

blocks/header/header.css, blocks/header/header.js
Test URLs:
- After: https://clear-search-btn--world-bank--aemsites.aem.live/ext/en/home
=> Add clear icon to search input

blocks/curated-cards/curated-cards.css, blocks/curated-cards/curated-cards.js, blocks/teaser/teaser.js
Test URLs:
- After: https://make-h1--world-bank--aemsites.aem.live/ext/en/home
=> Update heading for leader and teaser

blocks/header/header.css, blocks/header/header.js
Test URLs:
- After: https://trending--world-bank--aemsites.aem.live/ext/en/home
https://trending--world-bank--aemsites.aem.live/ext/ar/home
=> Add trending data to the header

blocks/tabs/_tabs.json, component-models.json
Test URLs:
- After: https://custom-url--world-bank--aemsites.aem.live/ext/en/who-we-are/leadership/axel-van-trotsenburg
=> updated tabs authoring

blocks/live-now/live-now.css, blocks/live-now/live-now.js
Test URLs:
- Before: https://main--world-bank--aemsites.aem.live/ext/ar/drafts/thomas/live-modal
- After: https://modal-language--world-bank--aemsites.aem.live/ext/ar/drafts/thomas/live-modal
=> Language specific API call in live modal

.eslintrc.js, blocks/tabs/_tabs.json, component-models.json
Test URLs:
- After: https://tab-custom--world-bank--aemsites.aem.live/ext/en/who-we-are/leadership/axel-van-trotsenburg
=> updated authroring for tabs

blocks/mini-cards/mini-cards.js, scripts/utils.js
This reverts commit 8cfddf7004678cd46f92b64213e8e892d84f5d8e.
Test URLs:
- After: https://revert-467-modal-language--world-bank--aemsites.aem.live/ext/en/home
=> Revert "Mini card update to not break on tag update (#467)"

blocks/tabs/_tabs.json, component-models.json
Test URLs:
- After: https://tab-custom--world-bank--aemsites.aem.live/ext/en/who-we-are/leadership/axel-van-trotsenburg
=> Tab custom

blocks/tabs/tabs.js
Test URLs:
- After: https://tabs-updated--world-bank--aemsites.aem.live/
=> tabs-updated

blocks/tabs/tabs.js
Test URLs:
- After: https://tab-final--world-bank--aemsites.aem.live/
=> updated tabs

blocks/tabs/tabs.js
Test URLs:
- After: https://tabs-checks--world-bank--aemsites.aem.live/ext/en/who-we-are/leadership/axel-van-trotsenburg
=> tabs - fix load more

blocks/bio-detail/bio-detail.js, blocks/priority-list/priority-list.js
Test URLs:
- After: https://analytics--world-bank--aemsites.aem.live/ext/en/home
=> Localized tags in priority list

blocks/live-now/live-now.css, blocks/live-now/live-now.js
Test URLs:
- Before: https://main--world-bank--aemsites.aem.live/ext/en/drafts/michael/test
- After: https://priority-bugs--world-bank--aemsites.aem.live/ext/en/drafts/michael/test
=> Live now clickable link

blocks/header/header.js, blocks/header/language-selector.js, scripts/utils.js
Test URLs:
- After: https://global-domain-config--world-bank--aemsites.aem.live/ext/en/home
=> Language selector to follow site domain config

blocks/curated-cards/curated-cards.css
Test URLs:
- After: https://curated-card-btn--world-bank--aemsites.aem.live/ext/en/home
=> fix curated cards button ellipsis

scripts/delayed.js
Test URLs:
- After: https://rum-collection--world-bank--aemsites.aem.live/ext/en/home
=> Collecting RUM data

blocks/bio-detail/bio-detail.css, blocks/footer/footer.css, blocks/tabs/tabs.css, blocks/tabs/tabs.js, styles/styles.css
Test URLs:
- Before: https://main--world-bank--aemsites.aem.live/ext/ar/home
- After: https://adobe-prod-sheet--world-bank--aemsites.aem.live/ext/ar/home
=> fix for adobe prod issues -logo width and arabic tab arrows

blocks/live-now/live-now.js
Test URLs:
- Before: https://main--world-bank--aemsites.aem.live/ext/en/drafts/michael/test
- After: https://live-now-date--world-bank--aemsites.aem.live/ext/en/drafts/michael/test
=> Convert to est for livenow modal

blocks/footer/footer.css
Test URLs:
- After: https://russian-footer--world-bank--aemsites.aem.live/ext/en/home
=> Russian footer css enhancements to fit large links

blocks/data-cards/data-cards.css, blocks/explore-cards/explore-cards.css, blocks/header/header.css, blocks/measuring-impact-cards/measuring-impact-cards.css, blocks/research-publications-cards/research-publications-cards.css, blocks/teaser/teaser.css
Test URLs:
- After: https://authoring-sheet-fixes--world-bank--aemsites.aem.live/ext/en/home
=> Authoring sheet fixes

blocks/data-cards/data-cards.css, blocks/teaser/teaser.css
Test URLs:
- Before: https://main--world-bank--aemsites.aem.live/ext/en/who-we-are/leadership
- After: https://p1-issues--world-bank--aemsites.aem.live/ext/en/who-we-are/leadership
=> p1 issues from document
